linters:
  enable-all: true
  disable:
    - varnamelen
    - depguard
    - godox
    - testpackage
    - exhaustivestruct
    - wsl
    - revive
    - ireturn
    - exhaustruct
    - misspell
    - gomnd
    - paralleltest
    - goerr113
    - rowserrcheck
    - tagalign
    - forbidigo
    - gci
    - gofumpt
    - godot
    - goimports
    - gochecknoglobals
    - errname
    - funlen        #Del
    - staticcheck   #Del
    - sqlclosecheck #Del
    - inamedparam   #Errors
    - testifylint   #Errors
    - gofmt         #Errors
    - deadcode      #Warnings
    - golint        #Warnings
    - scopelint     #Warnings
    - interfacer    #Warnings
    - nosnakecase   #Warnings
    - maligned      #Warnings
    - structcheck   #Warnings
    - ifshort       #Warnings
    - varcheck      #Warnings