version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5435:5432" # Исправил порт для PostgreSQL
    volumes:
      - ./internal/common/postgresql/schema/:/docker-entrypoint-initdb.d/
  
  main:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8004:8004"
    environment:
      SOME_ENV_VARIABLE: some_value
    networks:
      - mynetwork # Указываем сеть, чтобы оба контейнера были в одной сети

networks:
  mynetwork: # Создаем сеть
    driver: bridge