version: '3.8'

networks:
  app-network:

services:
  server:
    build:
      context: .
      dockerfile: ./build/Dockerfile
    restart: on-failure
    networks:
      app-network:
    ports:
      - "8080:8080"
    depends_on:
      - db
    # command: [".scripts/wait-for-it.sh", "db:5432", "--", "./app"]
    env_file:
      - .env

  db:
    image: postgres:latest
    restart: on-failure
    networks:
      app-network:
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./internal/common/postgresql/schema/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
