version: '3.8'

services:

  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5433:5433
    volumes:
      - ./internal/common/postgresql/schema/:/docker-entrypoint-initdb.d/