version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  server:
    build:
      context: .
      dockerfile: ./build/Dockerfile
    restart: on-failure
    networks:
      - app-network
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    volumes:
      - type: bind
        source: /images # тут должна быть папка фронта для фотографий на машине(заменить!)
        target: /images

  db:
    image: postgres:latest
    restart: on-failure
    networks:
      - app-network
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./internal/common/postgresql/schema/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    image: redis:latest
    restart: on-failure
    networks:
      - app-network
    ports:
      - "6379:6379"
