  
services:  
  db:
    container_name: hammy-db
    image: postgres:latest
    restart: always
    networks:
      - hammy-network
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PORT: ${DB_PORT}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5436:5432"
    volumes:
      - ./build/schema/:/docker-entrypoint-initdb.d/
 
  redis:
    container_name: hammy-redis
    image: redis:latest
    networks:
      - hammy-network
    restart: on-failure
    ports:
      - "6379:6379"

  # prometheus:
  #   container_name: prometheus
  #   image: prom/prometheus:latest
  #   volumes:
  #     - ./metrics/prometheus:/etc/prometheus
  #   ports:
  #     - "9090:9090"

  # nodeexporter:
  #   container_name: node_exporter
  #   image: prom/node-exporter
  #   volumes:
  #     - /proc:/host/proc:ro
  #     - /sys:/host/sys:ro
  #     - /:/rootfs:ro
  #   restart: unless-stopped
  #   ports:
  #     - "9100:9100"


  # grafana:
  #   container_name: grafana
  #   image: grafana/grafana-oss:9.4.3
  #   user: '0'
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - type: bind
  #       source: /home/ubuntu/grafana_metrics
  #       target: /var/lib/grafana


networks:
  hammy-network:
    driver: bridge
