  
services:  
  db:
    container_name: hammy-db
    image: postgres:latest
    restart: always
    networks:
      - hammy-network
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PORT: ${DB_PORT}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5436:5432"
    volumes:
      - ./build/schema/:/docker-entrypoint-initdb.d/
 
  redis:
    container_name: hammy-redis
    image: redis:latest
    networks:
      - hammy-network
    restart: on-failure
    ports:
      - "6379:6379"
  
networks:
  hammy-network:
    driver: bridge
