  
services:  
  db:
    image: postgres:latest
    restart: always
    networks:
      - app-network
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PORT: ${DB_PORT}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./cmd/api/init/db/postgresql/schema/:/docker-entrypoint-initdb.d/
 
  redis:
    image: redis:latest
    networks:
      - app-network
    restart: on-failure
    ports:
      - "6379:6379"
  
networks:
  app-network:
    driver: bridge
