// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson349b126bDecodeGithubComGoParkMailRu20232HamsterInternalModels(in *jlexer.Lexer, out *DeleteInAccount) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "user_id":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.UserID).UnmarshalText(data))
			}
		case "account_id":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.AccountID).UnmarshalText(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson349b126bEncodeGithubComGoParkMailRu20232HamsterInternalModels(out *jwriter.Writer, in DeleteInAccount) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"user_id\":"
		out.RawString(prefix[1:])
		out.RawText((in.UserID).MarshalText())
	}
	{
		const prefix string = ",\"account_id\":"
		out.RawString(prefix)
		out.RawText((in.AccountID).MarshalText())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v DeleteInAccount) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson349b126bEncodeGithubComGoParkMailRu20232HamsterInternalModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v DeleteInAccount) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson349b126bEncodeGithubComGoParkMailRu20232HamsterInternalModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *DeleteInAccount) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson349b126bDecodeGithubComGoParkMailRu20232HamsterInternalModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *DeleteInAccount) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson349b126bDecodeGithubComGoParkMailRu20232HamsterInternalModels(l, v)
}
func easyjson349b126bDecodeGithubComGoParkMailRu20232HamsterInternalModels1(in *jlexer.Lexer, out *AddUserAccount) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "login":
			out.Login = string(in.String())
		case "account_id":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.AccountID).UnmarshalText(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson349b126bEncodeGithubComGoParkMailRu20232HamsterInternalModels1(out *jwriter.Writer, in AddUserAccount) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"login\":"
		out.RawString(prefix[1:])
		out.String(string(in.Login))
	}
	{
		const prefix string = ",\"account_id\":"
		out.RawString(prefix)
		out.RawText((in.AccountID).MarshalText())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AddUserAccount) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson349b126bEncodeGithubComGoParkMailRu20232HamsterInternalModels1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AddUserAccount) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson349b126bEncodeGithubComGoParkMailRu20232HamsterInternalModels1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AddUserAccount) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson349b126bDecodeGithubComGoParkMailRu20232HamsterInternalModels1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AddUserAccount) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson349b126bDecodeGithubComGoParkMailRu20232HamsterInternalModels1(l, v)
}
