basePath: /user/{userID}/account/feed
host: localhost:8090
info:
  contact:
    email: dimka.komarov@bk.ru
    name: Hamster API Support
  description: Server API for Hamster Money Service Application
  title: Hamster API
  version: 1.0.1
paths: {}
swagger: "2.0"
