version: '3.8'

services:
  db:
    image: postgres:latest
    restart: on-failure
    environment:
      POSTGRES_DB: HammyWallets
      POSTGRES_USER: Hamster
      POSTGRES_PASSWORD: hammy
    volumes:
      - ./db/migrations/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U Hamster -d HammyWallets"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: hammy@mail.com
      PGADMIN_DEFAULT_PASSWORD: hammy
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data: