// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package category

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson12bfe9e7DecodeGithubComGoParkMailRu20232HamsterInternalMicroservicesCategory(in *jlexer.Lexer, out *TagUpdateInput) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "user_id":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.UserID).UnmarshalText(data))
			}
		case "parent_id":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.ParentID).UnmarshalText(data))
			}
		case "image_id":
			out.Image = int(in.Int())
		case "name":
			out.Name = string(in.String())
		case "show_income":
			out.ShowIncome = bool(in.Bool())
		case "show_outcome":
			out.ShowOutcome = bool(in.Bool())
		case "regular":
			out.Regular = bool(in.Bool())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson12bfe9e7EncodeGithubComGoParkMailRu20232HamsterInternalMicroservicesCategory(out *jwriter.Writer, in TagUpdateInput) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"user_id\":"
		out.RawString(prefix[1:])
		out.RawText((in.UserID).MarshalText())
	}
	{
		const prefix string = ",\"parent_id\":"
		out.RawString(prefix)
		out.RawText((in.ParentID).MarshalText())
	}
	{
		const prefix string = ",\"image_id\":"
		out.RawString(prefix)
		out.Int(int(in.Image))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"show_income\":"
		out.RawString(prefix)
		out.Bool(bool(in.ShowIncome))
	}
	{
		const prefix string = ",\"show_outcome\":"
		out.RawString(prefix)
		out.Bool(bool(in.ShowOutcome))
	}
	{
		const prefix string = ",\"regular\":"
		out.RawString(prefix)
		out.Bool(bool(in.Regular))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v TagUpdateInput) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson12bfe9e7EncodeGithubComGoParkMailRu20232HamsterInternalMicroservicesCategory(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TagUpdateInput) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson12bfe9e7EncodeGithubComGoParkMailRu20232HamsterInternalMicroservicesCategory(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TagUpdateInput) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson12bfe9e7DecodeGithubComGoParkMailRu20232HamsterInternalMicroservicesCategory(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TagUpdateInput) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson12bfe9e7DecodeGithubComGoParkMailRu20232HamsterInternalMicroservicesCategory(l, v)
}
func easyjson12bfe9e7DecodeGithubComGoParkMailRu20232HamsterInternalMicroservicesCategory1(in *jlexer.Lexer, out *TagInput) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "user_id":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.UserId).UnmarshalText(data))
			}
		case "parent_id":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.ParentId).UnmarshalText(data))
			}
		case "image_id":
			out.Image = int(in.Int())
		case "name":
			out.Name = string(in.String())
		case "show_income":
			out.ShowIncome = bool(in.Bool())
		case "show_outcome":
			out.ShowOutcome = bool(in.Bool())
		case "regular":
			out.Regular = bool(in.Bool())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson12bfe9e7EncodeGithubComGoParkMailRu20232HamsterInternalMicroservicesCategory1(out *jwriter.Writer, in TagInput) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"user_id\":"
		out.RawString(prefix[1:])
		out.RawText((in.UserId).MarshalText())
	}
	{
		const prefix string = ",\"parent_id\":"
		out.RawString(prefix)
		out.RawText((in.ParentId).MarshalText())
	}
	{
		const prefix string = ",\"image_id\":"
		out.RawString(prefix)
		out.Int(int(in.Image))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"show_income\":"
		out.RawString(prefix)
		out.Bool(bool(in.ShowIncome))
	}
	{
		const prefix string = ",\"show_outcome\":"
		out.RawString(prefix)
		out.Bool(bool(in.ShowOutcome))
	}
	{
		const prefix string = ",\"regular\":"
		out.RawString(prefix)
		out.Bool(bool(in.Regular))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v TagInput) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson12bfe9e7EncodeGithubComGoParkMailRu20232HamsterInternalMicroservicesCategory1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TagInput) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson12bfe9e7EncodeGithubComGoParkMailRu20232HamsterInternalMicroservicesCategory1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TagInput) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson12bfe9e7DecodeGithubComGoParkMailRu20232HamsterInternalMicroservicesCategory1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TagInput) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson12bfe9e7DecodeGithubComGoParkMailRu20232HamsterInternalMicroservicesCategory1(l, v)
}
func easyjson12bfe9e7DecodeGithubComGoParkMailRu20232HamsterInternalMicroservicesCategory2(in *jlexer.Lexer, out *TagDeleteInput) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.ID).UnmarshalText(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson12bfe9e7EncodeGithubComGoParkMailRu20232HamsterInternalMicroservicesCategory2(out *jwriter.Writer, in TagDeleteInput) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.RawText((in.ID).MarshalText())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v TagDeleteInput) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson12bfe9e7EncodeGithubComGoParkMailRu20232HamsterInternalMicroservicesCategory2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TagDeleteInput) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson12bfe9e7EncodeGithubComGoParkMailRu20232HamsterInternalMicroservicesCategory2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TagDeleteInput) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson12bfe9e7DecodeGithubComGoParkMailRu20232HamsterInternalMicroservicesCategory2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TagDeleteInput) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson12bfe9e7DecodeGithubComGoParkMailRu20232HamsterInternalMicroservicesCategory2(l, v)
}
func easyjson12bfe9e7DecodeGithubComGoParkMailRu20232HamsterInternalMicroservicesCategory3(in *jlexer.Lexer, out *CategoryCreateResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "category_id":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.CategoryID).UnmarshalText(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson12bfe9e7EncodeGithubComGoParkMailRu20232HamsterInternalMicroservicesCategory3(out *jwriter.Writer, in CategoryCreateResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"category_id\":"
		out.RawString(prefix[1:])
		out.RawText((in.CategoryID).MarshalText())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CategoryCreateResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson12bfe9e7EncodeGithubComGoParkMailRu20232HamsterInternalMicroservicesCategory3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CategoryCreateResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson12bfe9e7EncodeGithubComGoParkMailRu20232HamsterInternalMicroservicesCategory3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CategoryCreateResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson12bfe9e7DecodeGithubComGoParkMailRu20232HamsterInternalMicroservicesCategory3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CategoryCreateResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson12bfe9e7DecodeGithubComGoParkMailRu20232HamsterInternalMicroservicesCategory3(l, v)
}
