// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package transfer_models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonF13216eaDecodeGithubComGoParkMailRu20232HamsterInternalMicroservicesUserDeliveryHttpTransferModels(in *jlexer.Lexer, out *UserUdate) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "username":
			out.Username = string(in.String())
		case "planned_budget":
			out.PlannedBudget = float64(in.Float64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonF13216eaEncodeGithubComGoParkMailRu20232HamsterInternalMicroservicesUserDeliveryHttpTransferModels(out *jwriter.Writer, in UserUdate) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"username\":"
		out.RawString(prefix[1:])
		out.String(string(in.Username))
	}
	{
		const prefix string = ",\"planned_budget\":"
		out.RawString(prefix)
		out.Float64(float64(in.PlannedBudget))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UserUdate) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonF13216eaEncodeGithubComGoParkMailRu20232HamsterInternalMicroservicesUserDeliveryHttpTransferModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UserUdate) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonF13216eaEncodeGithubComGoParkMailRu20232HamsterInternalMicroservicesUserDeliveryHttpTransferModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UserUdate) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonF13216eaDecodeGithubComGoParkMailRu20232HamsterInternalMicroservicesUserDeliveryHttpTransferModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UserUdate) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonF13216eaDecodeGithubComGoParkMailRu20232HamsterInternalMicroservicesUserDeliveryHttpTransferModels(l, v)
}
