// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Fluire API Support",
            "email": "dimka.komarov@bk.ru"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/user/{userID}/actualBudget": {
            "get": {
                "description": "Get User actual budget",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Get Actual Budget",
                "responses": {
                    "200": {
                        "description": "Show actual budget",
                        "schema": {
                            "$ref": "#/definitions/http.budgetActualResponse"
                        }
                    },
                    "400": {
                        "description": "Client error",
                        "schema": {
                            "$ref": "#/definitions/http.Error"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/http.Error"
                        }
                    }
                }
            }
        },
        "/api/user/{userID}/balance": {
            "get": {
                "description": "Get User balance",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Get Balance",
                "responses": {
                    "200": {
                        "description": "Show balance",
                        "schema": {
                            "$ref": "#/definitions/http.balanceResponse"
                        }
                    },
                    "400": {
                        "description": "Client error",
                        "schema": {
                            "$ref": "#/definitions/http.Error"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/http.Error"
                        }
                    }
                }
            }
        },
        "/api/user/{userID}/plannedBudget": {
            "get": {
                "description": "Get User planned budget",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Get Planned Budget",
                "responses": {
                    "200": {
                        "description": "Show planned budget",
                        "schema": {
                            "$ref": "#/definitions/http.budgetPlannedResponse"
                        }
                    },
                    "400": {
                        "description": "Client error",
                        "schema": {
                            "$ref": "#/definitions/http.Error"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/http.Error"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "http.Error": {
            "type": "object"
        },
        "http.balanceResponse": {
            "type": "object",
            "properties": {
                "balance": {
                    "type": "number"
                }
            }
        },
        "http.budgetActualResponse": {
            "type": "object",
            "properties": {
                "planned_balance": {
                    "type": "number"
                }
            }
        },
        "http.budgetPlannedResponse": {
            "type": "object",
            "properties": {
                "planned_balance": {
                    "type": "number"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.1",
	Host:             "localhost:8090",
	BasePath:         "/user/{userID}/account/feed",
	Schemes:          []string{},
	Title:            "Fluire API",
	Description:      "Server API for Fluire Streaming Service Application",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
