name: CI

on: [push, pull_request]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.17'

      - name: Cache Go modules
        uses: actions/cache@v3
        id: go-cache
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-

      - if: steps.go-cache.outputs.cache-hit != 'true'
        run: go mod download

      - name: Run Unit tests
        run: |
          go test -race ./...

      - name: Verify dependencies
        run: go mod verify

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.17'

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests
        run: go test -race -vet=off -run '!(ws|server)' ./...
